version: '3.9'
services:
  gateway-service:
    container_name: gateway_service
    build:
      context: .
      dockerfile: ../services/Gateway/src/Gateway/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - redis
  
  workflow-service:
    container_name: workflow_service
    build:
      context: .
      dockerfile: ../services/WorkflowService/src/WorkflowService/Dockerfile
    ports:
      - "5010:8080"
    depends_on:
      - workflow-db
      - redis
  
  workflow-db:
    image: postgres:16
    container_name: workflow_db
    restart: always
    environment:
      POSTGRES_DB: foundry_db
      POSTGRES_USER: foundry
      POSTGRES_PASSWORD: foundry
    ports:
      - "5433:5432"
    volumes:
      - workflow_pgdata:/var/lib/postgresql/data
     
  identity-service:
    container_name: identity_service
    build:
      context: .
      dockerfile: ../services/IdentityServer/src/IdentityServer/Dockerfile
    ports:
      - "5020:8080"
    depends_on:
      - workflow-db
      - redis

  identity-db:
    image: postgres:16
    restart: always
    container_name: identity_db
    environment:
      POSTGRES_USER: foundry
      POSTGRES_PASSWORD: foundry
      POSTGRES_DB: foundry_db
    ports:
      - "5434:5432"
    volumes:
      - identitydata:/var/lib/postgresql/data
        
  client-service:
    container_name: client_service
    build:
      context: .
      dockerfile: ../services/ClientService/src/ClientService/Dockerfile
    ports:
      - "5030:8080"
    depends_on:
      - workflow-db
      - redis

  client-db:
    image: postgres:16
    container_name: client_db
    restart: always
    environment:
      POSTGRES_DB: foundry_db
      POSTGRES_USER: foundry
      POSTGRES_PASSWORD: foundry
    ports:
      - "5435:5432"
    volumes:
      - client_pgdata:/var/lib/postgresql/data
  
  telegram-service:
    container_name: telegram_service
    build:
      context: .
      dockerfile: ../services/TelegramService/src/TelegramService/Dockerfile
    ports:
      - "5040:8080"
    depends_on:
      - client-db
      - redis
  
  telegram-db:
    image: postgres:16
    container_name: telegram_db
    restart: always
    environment:
      POSTGRES_DB: foundry_db
      POSTGRES_USER: foundry
      POSTGRES_PASSWORD: foundry
    ports:
      - "5436:5432"
    volumes:
      - workflow_pgdata:/var/lib/postgresql/data
      
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6380:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis:/data
        
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
        
volumes:
  identitydata:
  workflow_pgdata:
  client_pgdata:
  redis:
