# Allow local socket connections
local   all             all                                     trust
# Allow connections from any host in Docker network (no SSL) with password
host    all             all             0.0.0.0/0               scram-sha-256
host    all             all             ::0/0                   scram-sha-256
