<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../../../tests/Directory.Build.props" />
  <ItemGroup>
    <ProjectReference Include="../../src/ClientService/ClientService.csproj" />
    <ProjectReference Include="../../../../tests/ChatFoundry.TestInfrastructure/ChatFoundry.TestInfrastructure.csproj" />
  </ItemGroup>
</Project>